### ISSUE TITLE
warpAffine get a inverse point

### ISSUE THREAD

**Issue by Zeleni9** [david-wb/gaze-estimation#5]
Hi David, 

I have a quick question about **warpAffine**. The full frame gets into the **segment_eyes()** method and there _transform_mat_ and _inv_transform_mat_ are calculated and cv2.warpAffine is called to get eye_image (160, 96). I have a question about getting the pupil center point (x,y) I predict in the eye_image back into the full frame coordinate. 

If I understand this correct, when I do want to remap point back to full frame I will probably get a coordinates relative to 5_point facial landmarks which then can give me full frame coordinates for eye_center. **How can I approach it to get pupil_center from eye_image (160, 96) coordinates back to full image coordinates?** I have tried few approaches but nothing gives me relevant points. 

```
1)  #eye_center_full_frame = cv2.transformPerspective(eye_center_point, eye.eye_sample.transform_inv[:2, :])                                                                                                    
2)  #eye_center_full_frame = cv2.transform(eye_center_point, eye.eye_sample.transform_original[:2, :], (2,1), cv2.WARP_INVERSE_MAP)
```
or 

```
eye_center_array = np.array([[eye_center[0], eye_center[1]]], dtype=np.float32)
transformed_points = eye_center_array * eye.eye_sample.transform_inv[:2, :2]
```

Thanks 

**Edit:** 
I found a solution, not sure if it is inteded to be used like this. If I don't flip the image to show there is needed different change for eye.is_left. 

```
for eye in [left_eye, right_eye]:
    ... 

     if eye.eye_sample.is_left:
        eye_center_array = np.array([[160 - eye_center[0], eye_center[1], 1.0]], dtype=np.float32)
    else:
        eye_center_array = np.array([[eye_center[0], eye_center[1], 1.0]], dtype=np.float32)
                    
     transformed_points = np.asarray(np.matmul(eye_center_array, eye.eye_sample.transform_inv.T))[:, :2]    
    center = np.array(transformed_points).flatten()
  
    # Draw dots on eye center in full frame             
     cv2.circle(orig_frame, (int(center[0]), int(center[1])) , 3, (0,255,0),-1)            
     cv2.imshow("Webcam", cv2.flip(orig_frame, 1))
```

**Comment by david-wb** [comment]
@Zeleni9 It's been a while since I've looked at this code, but I believe the second to last eye landmark is the pupil center. That is where the direction arrow is drawn. See here
https://github.com/david-wb/gaze-estimation/blob/249691893a37944a03e4ad4a3448083b6f63af10/run_with_webcam.py#L96

Also all of the eye landmark coords are relative to the inner corner of the eye. That corner is detected by the face landmark detect (If I recall correctly.). 

As for the `warpAffine` and other transformation steps, I admit it is confusing, but the easiest way to see how it works is to start a new jupyter notebook and render the image after each transformation step. 

Hope that helps!
